config/routes.rb
Rails.application.routes.draw do
  
    get '/reviews/:id/specifications', :to => 'reviews#specifications'
    get '/reviews/combustion', :to => 'reviews#combustion'
    get '/reviews/electricos', :to => 'reviews#electricos'
    get '/homepage', :to => 'reviews#recent'
    get '/noticias', :to => 'articles#actualidad'
    get '/futuro', :to => 'articles#futuro'
    
    resources :reviews

    resources :articles

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    mount_uploader :picture, PictureUploader

    validates :title, 
        presence: true, length: { maximum: 25 }
    validates :description,
        length: { maximum: 1800}, length: { minimum: 20}
    validates :picture,
        presence: true
    validates :category,
        presence: true
end

app/models/review.rb
class Review < ApplicationRecord
    has_many :specifications, dependent: :destroy
    has_many :sections, dependent: :destroy
    accepts_nested_attributes_for :sections, allow_destroy: true, reject_if: :all_blank
    accepts_nested_attributes_for :specifications, allow_destroy: true, reject_if: :all_blank
    def review_image
        sections.all.map(&:picture_url).first().url
    end

    validates :title, 
        presence: true, length: { maximum: 25 }
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :review, optional: true
  mount_uploader :picture_url, PictureUploader

  validates :title, 
      presence: true, length: { maximum: 25 }
  validates :body,
      length: { maximum: 1200}, length: { minimum: 20}
  validates :picture_url,
      presence: true
end

app/models/specification.rb
class Specification < ApplicationRecord
  belongs_to :review

  validates :prestacion, 
    presence: true, length: { maximum: 30 }
  validates :valor,
    presence: true, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :cors_headers
    skip_before_action :verify_authenticity_token
    private
        def cors_headers
            headers['Access-Control-Allow-Origin'] = '*'
            headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
            headers['Access-Control-Request-Method'] = '*'
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    def new
        @article = Article.new
    end

    def index
        @articles = Article.all
    end

    def create
        #render plain: params[:new].inspect
        @article = Article.new(article_params)

        if @article.save
            return redirect_to articles_path
        end

        render :new
    end

    def show
    end

    def actualidad
        render :json => Article.where(category: "actualidad").to_json()
      end
    
      def futuro
        render :json => Article.where(category: "futuro").to_json()
      end

    def edit
    end

    def update
        @article.update article_params
        redirect_to @article
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def article_params
        params.require(:article).permit(:title, :description, :picture, :category, :time)
    end

    def set_article
        @article = Article.find params[:id]
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  
  def new
    @review = Review.new
    @review.specifications.build
    @review.sections.build
  end
  
  def index
    @reviews = Review.all
  end

  def specifications
    @specifications = Review.find(params[:id]).specifications
    render :json => @specifications.to_json()
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      return redirect_to reviews_path
    end

    render :new
  end

  def show
    @review = Review.find(params[:id])
    render :json => @review.to_json(:include => [:sections, :specifications])
  end

  def recent
    render :json => Review.last(3).to_json(:include => [:sections], methods: :review_image)
  end

  def combustion
    render :json => Review.where(category: "combustion").to_json(methods: :review_image)
  end

  def electricos
    render :json => Review.where(category: "electrico").to_json(methods: :review_image)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  private
    def review_params
      params.require(:review).permit(:title, :category, sections_attributes: Section.attribute_names.map(&:to_sym).push(:_destroy), specifications_attributes: Specification.attribute_names.map(&:to_sym).push(:_destroy))
    end

    def set_review
      @review = Review.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_row(name, f, association, **args)
        new_object = f.object.send(association).klass.new
        id = new_object.object_id
        fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
            render(association.to_s.singularize, f:builder)
        end
        link_to(name, '#', class:"add_fields" + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class='col-4'>
  <figure class="figure">
    <figcaption class="figure-caption">
      <%= image_tag(article.picture.url, :width => 80, :height => 80) unless article.picture.url.nil? %>
      <%= article.title %>
      <%= link_to 'Show', article_path(article) %> 
      <%= link_to 'Edit', edit_article_path(article) %> 
      <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'sure?'} %> 
    </figcaption>
  </figure>
</div>

app/views/articles/_form.html.erb
<%- if @article.errors.any? %>
    <div class='alert alert-danger'>
        <h4 class='alert-heading'>Oh no!</h4>
        <p> Ha ocurrido un error </p>
    </div>
<% end %>

<div class='form-group'>
    <%= form_for @article, :html => {:multipart => true} do |f| %>

        <%= f.label :title %> <br>
        <%= f.text_field :title, class: 'form-control' %> 
        <%- if @article.errors[:title].any? %>
            <span class='badge badge-pill badge-danger'>
                <%= @article.errors[:title].first %>
            </span>
        <br>
        <% end %>
        <br>

        <%= f.label :description %> <br>
        <%= f.text_field :description, class: 'form-control' %>
        <%- if @article.errors[:description].any? %>
            <span class='badge badge-pill badge-danger'>
                <%= @article.errors[:description].first %>
            </span>
        <br>
        <% end %>
        <br>

        <%= f.label :picture %> <br>
        <%= f.file_field :picture %>
        <%- if @article.errors[:picture].any? %>
            <span class='badge badge-pill badge-danger'>
                <%= @article.errors[:picture].first %>
            </span>
        <br>
        <% end %>
        <br>

        <%= f.label :category %> <br>
        <%= f.text_field :category, class: 'form-control' %>
        <%- if @article.errors[:category].any? %>
            <span class='badge badge-pill badge-danger'>
                <%= @article.errors[:category].first %>
            </span>
        <br>
        <% end %>
        <br>
        
        <%= f.submit 'Enviar', :class => 'btn btn-primary' %>

    <% end %>
</div>

app/views/articles/edit.html.erb
<div class='container'>
    <p>EDITAR NOTICIA</p>
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class='container'>
    <div class='row'>
        <%= render @articles %> 
    </div>
</div>

app/views/articles/new.html.erb
<div class='container'>
    <p> CREAR NOTICIA </p>
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class='container'>
    <%= image_tag(@article.picture.url, :width => 80, :height => 80) unless @article.picture.url.nil? %>
    <%= @article.title %>
    <%= @article.description %>
    <%= @article.category %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CochesApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%- if @review.errors.any? %>
    <div class='alert alert-danger'>
        <h4 class='alert-heading'>Oh no!</h4>
        <p> Ha ocurrido un error </p>
    </div>
<% end %>

<%= simple_form_for(@review) do |f| %>
    <%= f.error_notification %>

    <div class  = "form-inputs">
        <%= f.input :title %>
        <%- if @review.errors[:title].any? %>
            <span class='badge badge-pill badge-danger'>
                <%= @review.errors[:title].first %>
            </span>
        <br>
        <% end %>
        <br>
    </div>

    <div class  = "form-inputs">
        <%= f.input :category %>
    </div>

    <table class = "table">
        <thead>
            <tr>
                <th/>
                <th>Section title</th>
                <th>Section body</th>
                <th>Image</th>
            </tr>
            
        <br>
            </tr>
        </thead>
        <tbody class = "section_fields">
            <%= f.simple_fields_for :sections do |builder| %>
                <%= render  "section", f: builder %>
            <% end %>
        </tbody>
    </table>

    <table class = "table">
        <thead>
            <tr>
                <th/>
                <th>Specification name</th>
                <th>Specification value</th>
            </tr>
        </thead>
        <tbody class = "specification_fields">
            <%= f.simple_fields_for :specifications do |builder| %>
                <%= render  "specification", f: builder %>
            <% end %>
        </tbody>
    </table>

    <div class = "form-actions">
        <%= f.button :submit %>
        <%= link_to_add_row('Add section', f, :sections, class: '_section_btn btn-primary' ) %>
        <%= link_to_add_row('Add specification', f, :specifications, class: '_specification_btn btn-primary' ) %>
    </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="container">
    <tr>
        <td><%= review.title %></td>
        <td> <%= link_to  "Show", review_path(review) %></td>
        <td> <%= link_to  "Destroy", review_path(review), method: :delete %></td>
    </tr>
</div>

app/views/reviews/_section.html.erb
<tr>
    <td>
        <%= f.input_field :_destroy, as: :hidden %>
        <%= link_to 'Delete', '#', class: 'remove_record' %>
    </td>
    <td><%=f.input :title, label: false %></td>
    <td><%=f.input :body, label: false, as: :text %></td>
    <td><%=f.input :picture_url, label: false, as: :file %></td>
</tr>

app/views/reviews/_specification.html.erb
<tr>
    <td>
        <%= f.input_field :_destroy, as: :hidden %>
        <%= link_to 'Delete', '#', class: 'remove_record' %>
    </td>
    <td><%=f.input :prestacion, label: false %></td>
    <td><%=f.input :valor, label: false, as: :text %></td>
</tr>

app/views/reviews/index.html.erb
<%= link_to 'New review', new_review_path %>
<table>
    <%= render @reviews %>
</table>

app/views/reviews/new.html.erb
<div class="container">    
    <p> CREAR REVIEW </p> 
    <%= render 'form' %>
</div>

app/views/reviews/show.html.erb
<div class="container">
  <div class='col-4'>
  <figure class="figure">
      <figcaption class="figure-caption">
        <h3>
          <%= @review.title %>
        </h3>
        <h4>Sections</h4>
        <% @review.sections.each do |section| %>
          <h5><%= section.title %></h5>
          <p><%= section.body %></p>
          <%= image_tag(section.picture_url.url, :width => 80, :height => 80) unless section.picture_url.url.nil? %>
        <% end %>
        <h4>Specifications</h4>
        <table>
          <th>Prestacion</th>
          <th>Valor</th>
          <% @review.specifications.each do |specification| %>
          <tbody>
            <tr>
              <td><%= specification.prestacion %></td>
              <td><%= specification.valor %></td>
            </tr>
          <% end %>
        </table>
      </figcaption>
    </figure>
  </div>
</div>